[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

time = { version="^0.3", features=["parsing", "macros", "local-offset"] }
reqwest = { version="^0.11", features=["blocking", "json"] }
serde = { version="^1.0", features=["derive"] }
serde_json = { version="^1.0" }
serde_yaml = { version="^0.9" }
regex = { version="^1.10" }